<%@ Page Language="C#" AutoEventWireup="true" CodeFile="ManageGallery.aspx.cs" Inherits="Cricket_club_management_system.ManageGallery" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <style>
      body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #e3f2fd;
    }
    .sidebar {
        width: 250px;
        height: 100vh;
        background: #478cc8;
        color: white;
        position: fixed;
        padding-top: 20px;
    }
    .sidebar a {
        display: block;
        padding: 15px;
        color: white;
        text-decoration: none;
        transition: 0.3s;
    }
    .sidebar a:hover {
        background: #2f75b3;
    }
    .main-content {
        margin-left: 260px;
        padding: 20px;
    }
    .card {
        background: #ffffff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.2);
        margin-bottom: 20px;
        transition: transform 0.3s;
    }
    .card:hover {
        transform: scale(1.05);
    }
    .card a {
        background-color: #1b5e20;
        color: white;
        padding: 10px 20px;
        text-decoration: none;
        font-weight: bold;
        border-radius: 5px;
        margin-right: 20px;
        display: inline-block;
    }
    .card a:hover {
        background-color: #388e3c;
    }
</style>
</head>
<body>
    <form id="form1" runat="server">
                <div>
            <div class="sidebar">
    <h2 style="text-align:center;">Admin Panel</h2>
    <a href="dashboard.aspx">Dashboard</a>
    <a href="ManageGallery.aspx">Upload Image</a>
    <a href="upload_reviews.aspx">Manage Reviews</a>
    <a href="Notice.aspx">Add Notice</a>
                <a href="uploadteammember.aspx">Manage Team Members</a>
    <a href="logout.aspx">Logout</a>
</div>
        <div class="main-content">
            <h2>Upload Image</h2>
            <p>&nbsp;</p>
            <p>&nbsp;</p>           
<a href="View_Gallery.aspx" style="background-color: black; color: white; padding: 10px 20px; text-decoration: none; font-weight: bold; border-radius: 5px; margin-right: 20px;">View Page</a><br /><br /><br /><br /><br /><br /><br />
            <br />
            <br />
&nbsp;<asp:Label ID="lblError" runat="server" CssClass="error" Visible="False"></asp:Label>
<asp:Label ID="lblSuccess" runat="server" CssClass="success" Visible="False"></asp:Label>

            <br />

            <asp:FileUpload ID="fileUploadImage" runat="server" /><br /><br />

<asp:Button ID="Button1" runat="server" Text="Submit" OnClick="btnSubmit_Click" /><br /><br />

<h3>Recent Image</h3>
<asp:Repeater ID="rptBlogs" runat="server">
    <ItemTemplate>
        <div style="border-bottom: 1px solid #ccc; margin-bottom: 10px; padding-bottom: 10px;">
        <%# Eval("ImageUrl") != DBNull.Value && Eval("ImageUrl").ToString() != "" 
     ? "<img src='" + Eval("ImageUrl") + "' class='blog-image' />" 
     : "" %>
        </div>
    </ItemTemplate>
</asp:Repeater>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
    AutoGenerateDeleteButton="True" 
    DataKeyNames="Id" DataSourceID="SqlDataSource1">
    <Columns>
        <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
        
        <asp:TemplateField HeaderText="Image">
            <ItemTemplate>
                <asp:Image ID="Image1" runat="server" ImageUrl='<%# Eval("ImageUrl") %>' Width="100px" Height="100px"/>
            </ItemTemplate>
        </asp:TemplateField>

    </Columns>
</asp:GridView>

<asp:SqlDataSource ID="SqlDataSource2" runat="server" 
    ConnectionString="<%$ ConnectionStrings:MyConnectionString %>" 
    SelectCommand="SELECT Id, ImageUrl FROM Gallery">
</asp:SqlDataSource>

                        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:MyConnectionString %>" SelectCommand="SELECT Id,ImageUrl FROM Gallery" DeleteCommand="DELETE FROM Gallery WHERE (Id=@Id)" UpdateCommand="UPDATE Gallery SET ImageUrl=@ImageUrl WHERE (Id=@Id)">
 <DeleteParameters>
     <asp:Parameter Name="Id" Type="Int32" />
 </DeleteParameters>    
                            </asp:SqlDataSource>
</div>
    </form>
</body>
</html>

















