<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Notice.aspx.cs" Inherits="Cricket_club_management_system.Notice" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <style>
      body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #e3f2fd;
    }
    .sidebar {
        width: 250px;
        height: 100vh;
        background: #478cc8;
        color: white;
        position: fixed;
        padding-top: 20px;
    }
    .sidebar a {
        display: block;
        padding: 15px;
        color: white;
        text-decoration: none;
        transition: 0.3s;
    }
    .sidebar a:hover {
        background: #2f75b3;
    }
    .main-content {
        margin-left: 260px;
        padding: 20px;
    }
    .card {
        background: #ffffff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.2);
        margin-bottom: 20px;
        transition: transform 0.3s;
    }
    .card:hover {
        transform: scale(1.05);
    }
    .card a {
        background-color: #1b5e20;
        color: white;
        padding: 10px 20px;
        text-decoration: none;
        font-weight: bold;
        border-radius: 5px;
        margin-right: 20px;
        display: inline-block;
    }
    .card a:hover {
        background-color: #388e3c;
    }
</style>
</head>
<body>
        <form id="form1" runat="server">
                <div>
            <div class="sidebar">
    <h2 style="text-align:center;">Admin Panel</h2>
    <a href="dashboard.aspx">Dashboard</a>
    <a href="ManageGallery.aspx">Upload Image</a>
    <a href="upload_reviews.aspx">Manage Reviews</a>
    <a href="Notice.aspx">Add Notice</a>
                <a href="uploadteammember.aspx">Manage Team Members</a>
    <a href="logout.aspx">Logout</a>
</div>
        <div class="main-content">
            <h2>Upload Notice</h2>

<asp:Label ID="lblError" runat="server" CssClass="error" Visible="False"></asp:Label>
<asp:Label ID="lblSuccess" runat="server" CssClass="success" Visible="False"></asp:Label>

<label>
                <br />
                Title:</label><br />
<asp:TextBox ID="txtTitle" runat="server" Width="100%"></asp:TextBox><br /><br />

<label>Description:<br />
            </label><br />
<asp:TextBox ID="txtDescription" runat="server" TextMode="MultiLine" Width="100%"></asp:TextBox><br />
            <br />
            <br />
<label>PostedDate:</label><br />
     <asp:TextBox ID="txtPostedDate" runat="server" TextMode="MultiLine" Width="100%"></asp:TextBox><br />

<asp:Button ID="btnSubmit" runat="server" Text="Submit" OnClick="btnSubmit_Click" /><br /><br />

<h3>Recent Notice</h3>
<asp:Repeater ID="rptBlogs" runat="server">
    <ItemTemplate>
        <div style="border-bottom: 1px solid #ccc; margin-bottom: 10px; padding-bottom: 10px;">
            <br />
            <h4><%# Eval("Title") %></h4>
            <p><b>Description:</b> <%# Eval("Description") %></p>
              <p><%# Eval("PostedDate") %></p>
        </div>
    </ItemTemplate>
</asp:Repeater>
     <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="NoticeId" DataSourceID="SqlDataSource1">
         <Columns>
             <asp:BoundField DataField="NoticeId" HeaderText="NoticeId" InsertVisible="False" ReadOnly="True" SortExpression="NoticeId" />
             <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" />
            
             <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
             <asp:BoundField DataField="PostedDate" HeaderText="PostedDate" SortExpression="PostedDate" />
         </Columns>
                </asp:GridView>

                <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:MyConnectionString %>" SelectCommand="SELECT  NoticeId,Title,Description,PostedDate FROM Notices" UpdateCommand="UPDATE Notices SET  Title=@Title,Description=@Description,PostedDate=@PostedDate WHERE(NoticeId=@NoticeId)"  DeleteCommand="DELETE FROM Notices WHERE(NoticeId=@NoticeId)">
                        <DeleteParameters>
                             <asp:Parameter Name="NoticeId" Type="Int32" />
                        </DeleteParameters>
                        <UpdateParameters>
                             <asp:Parameter Name="Title" Type="String" />
                            
                             <asp:Parameter Name="Description" Type="String" />
                             <asp:Parameter Name="PostedDate" Type="String" />
                             <asp:Parameter Name="NoticeId" Type="Int32" />
                        </UpdateParameters>
                </asp:SqlDataSource>
        </div>
    </form>
</body>
</html>
