<%@ Page Language="C#" AutoEventWireup="true" CodeFile="uploadteammember.aspx.cs" Inherits="Cricket_club_management_system.uploadteammember" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
   <title>Upload Team Member</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <style>
      body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #e3f2fd;
    }
    .sidebar {
        width: 250px;
        height: 100vh;
        background: #478cc8;
        color: white;
        position: fixed;
        padding-top: 20px;
    }
    .sidebar a {
        display: block;
        padding: 15px;
        color: white;
        text-decoration: none;
        transition: 0.3s;
    }
    .sidebar a:hover {
        background: #2f75b3;
    }
    .main-content {
        margin-left: 260px;
        padding: 20px;
    }
    .card {
        background: #ffffff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.2);
        margin-bottom: 20px;
        transition: transform 0.3s;
    }
    .card:hover {
        transform: scale(1.05);
    }
    .card a {
        background-color: #1b5e20;
        color: white;
        padding: 10px 20px;
        text-decoration: none;
        font-weight: bold;
        border-radius: 5px;
        margin-right: 20px;
        display: inline-block;
    }
    .card a:hover {
        background-color: #388e3c;
    }
</style>
</head>
<body>
    <form id="form1" runat="server">
            <div class="sidebar">
    <h2 style="text-align:center;">Admin Panel</h2>
    <a href="dashboard.aspx">Dashboard</a>
    <a href="ManageGallery.aspx">Upload Image</a>
    <a href="upload_reviews.aspx">Manage Reviews</a>
    <a href="Notice.aspx">Add Notice</a>
                <a href="uploadteammember.aspx">Manage Team Members</a>
    <a href="logout.aspx">Logout</a>
</div>
        <div class="main-content">
            <h2>Upload Team Member</h2>
            
            <asp:Label ID="lblName" runat="server" Text="Name:"></asp:Label>
            <asp:TextBox ID="txtName" runat="server"></asp:TextBox>
            <br /><br />
            
            <asp:Label ID="lblRole" runat="server" Text="Role:"></asp:Label>
            <asp:TextBox ID="txtRole" runat="server"></asp:TextBox>
            <br /><br />

            <asp:Label ID="lblDescription" runat="server" Text="Description:"></asp:Label>
            <asp:TextBox ID="txtdes" runat="server" TextMode="MultiLine"></asp:TextBox>
            <br /><br />

            <asp:Label ID="lblUpload" runat="server" Text="Upload Image:"></asp:Label>
            <asp:FileUpload ID="fileUpload" runat="server" />
            <br /><br />

            <asp:Button ID="btnUpload" runat="server" Text="Upload" OnClick="btnUpload_Click" />
            <br /><br />

            <asp:Label ID="lblMessage" runat="server" ForeColor="Red"></asp:Label>
        </div>
        <center><asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Id" DataSourceID="SqlDataSource1">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                <asp:BoundField DataField="Role" HeaderText="Role" SortExpression="Role" />
                <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
                <asp:BoundField DataField="Imagepath" HeaderText="Imagepath" SortExpression="Imagepath" />
            </Columns>
        </asp:GridView>
            </center>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:MyConnectionString %>" SelectCommand="SELECT  Id,Name,Role,Description,Imagepath FROM t_TeamMembers" UpdateCommand="UPDATE t_TeamMembers SET Name=@Name,role=@Role,Description=@Description,Imagepath=@Imagepath WHERE(Id=@Id)"  DeleteCommand="DELETE FROM t_TeamMembers WHERE(Id=@Id)">
            <DeleteParameters>
                        <asp:Parameter Name="Id" Type="Int32" />
                   </DeleteParameters>
                   <UpdateParameters>
                        <asp:Parameter Name="Name" Type="String" />
                        <asp:Parameter Name="Role" Type="String" />
                        <asp:Parameter Name="Description" Type="String" />
                        <asp:Parameter Name="Imagepath" Type="String" />
                        <asp:Parameter Name="Id" Type="Int32" />
                   </UpdateParameters>

        </asp:SqlDataSource>
    </form>

</body>
</html>
