<%@ Page Language="C#" AutoEventWireup="true" CodeFile="viewgroundbook.aspx.cs" Inherits="Cricket_club_management_system.viewgroundbook" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">  
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://kit.fontawesome.com/your-kit-id.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <style>
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f4f4f4;
    }
    .sidebar {
        width: 250px;
        height: 100vh;
        background: #333;
        color: white;
        position: fixed;
        padding-top: 20px;
    }
    .sidebar a {
        display: block;
        padding: 15px;
        color: white;
        text-decoration: none;
        transition: 0.3s;
    }
    .sidebar a:hover {
        background: #575757;
    }
    .main-content {
        margin-left: 260px;
        padding: 20px;
    }
    .card {
        background: white;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
        margin-bottom: 20px;
        transition: transform 0.3s;
    }
    .card:hover {
        transform: scale(1.05);
    }
</style>
            <script type="text/javascript">
            function PrintDiv() {

                var divContents = document.getElementById("contents").innerHTML;
                var originalContents = document.body.innerHTML;

                document.body.innerHTML = "<html><body>" + divContents + "</body></html>";
                window.print();
                document.body.innerHTML = originalContents;
            }
    </script>
</head>
    <body>
  
    <form id="form1" runat="server">
        <div>
                    <div>
            <div class="sidebar" >
    <h2 style="text-align:center;">Admin Panel</h2>
    <a href="dashboard.aspx">Dashboard</a>
    <a href="ManageGallery.aspx">Manage Gallery</a>
    <a href="upload_reviews.aspx">Manage Reviews</a>
    <a href="Notice.aspx">Manage Notice</a>
                <a href="uploadteammember.aspx">Manage Team Members</a>
    <a href="logout.aspx">Logout</a>
</div>
                        </div>
<div class="main-content" id="contents">
        <center><h2>Ground booking</h2>
<asp:GridView ID="GridView1" runat="server" 
    AutoGenerateColumns="False" 
    AutoGenerateDeleteButton="True" 
    AutoGenerateEditButton="True" 
    CssClass="custom-gridview"
    HeaderStyle-CssClass="grid-header"
    RowStyle-CssClass="grid-row"
    AlternatingRowStyle-CssClass="grid-alt-row"
    DataKeyNames="Id" 
    DataSourceID="SqlDataSource1" CellPadding="4" ForeColor="#333333" GridLines="None">     
<AlternatingRowStyle CssClass="grid-alt-row" BackColor="White"></AlternatingRowStyle>
    <Columns>         
        <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />         
        <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />         
        <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />         
        <asp:BoundField DataField="Contact" HeaderText="Contact" SortExpression="Contact" />         
        <asp:BoundField DataField="Purpose" HeaderText="Purpose" SortExpression="Purpose" />         
                
        <asp:BoundField DataField="FromDate" HeaderText="From Date" SortExpression="FromDate" />         
        <asp:BoundField DataField="EndDate" HeaderText="End Date" SortExpression="EndDate" />    
        <asp:BoundField DataField="TotalAmount" HeaderText="TotalAmount" SortExpression="TotalAmount" />  
    </Columns> 
    <EditRowStyle BackColor="#7C6F57" />
    <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />

<HeaderStyle CssClass="grid-header" BackColor="#1C5E55" Font-Bold="True" ForeColor="White"></HeaderStyle>

    <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />

<RowStyle CssClass="grid-row" BackColor="#E3EAEB"></RowStyle>
    <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
    <SortedAscendingCellStyle BackColor="#F8FAFA" />
    <SortedAscendingHeaderStyle BackColor="#246B61" />
    <SortedDescendingCellStyle BackColor="#D4DFE1" />
    <SortedDescendingHeaderStyle BackColor="#15524A" />
</asp:GridView>

        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:MyConnectionString %>" SelectCommand="SELECT Id, Name,Email,Email,Contact,Purpose,FromDate,EndDate,TotalAmount FROM GRNDBooking" DeleteCommand="DELETE FROM GRNDBooking WHERE (Id=@id)" UpdateCommand="UPDATE GRNDBooking SET Name=@Name,Email=@Email,Contact=@Contact,Purpose=@Purpose,FromDate=@FromDate,EndDate=@EndDate,TotalAmount=@TotalAmount WHERE (Id=@Id)">
        <DeleteParameters>
        <asp:Parameter Name="Id" Type="Int32" />
    </DeleteParameters>
    <UpdateParameters>
        <asp:Parameter Name="Name" Type="String" />
        <asp:Parameter Name="Email" Type="String" />
        <asp:Parameter Name="Contact" Type="String" />
        <asp:Parameter Name="Purpose" Type="String" />
    
         <asp:Parameter Name="FromDate" Type="DateTime" />
         <asp:Parameter Name="EndDate" Type="DateTime" />
          <asp:Parameter Name="TotalAmount" Type="String" />
    </UpdateParameters>
</asp:SqlDataSource>

            <asp:Button ID="btn_pdf" Text="Download" runat="server" OnClientClick="PrintDiv();return false;" />

            </div>
            
    </form>
      
                   

</body>
</html>
