<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="viewreg.aspx.cs" Inherits="Cricket_club_management_system.viewreg" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <style>
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f4f4f4;
    }
    .sidebar {
        width: 250px;
        height: 100vh;
        background: #333;
        color: white;
        position: fixed;
        padding-top: 20px;
    }
    .sidebar a {
        display: block;
        padding: 15px;
        color: white;
        text-decoration: none;
        transition: 0.3s;
    }
    .sidebar a:hover {
        background: #575757;
    }
    .main-content {
        margin-left: 260px;
        padding: 20px;
    }
    .card {
        background: white;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
        margin-bottom: 20px;
        transition: transform 0.3s;
    }
    .card:hover {
        transform: scale(1.05);
    }
</style>
            <script type="text/javascript">
        function PrintDiv() {

            var divContents = document.getElementById("contents").innerHTML;
            var originalContents = document.body.innerHTML;

            document.body.innerHTML = "<html><body>" + divContents + "</body></html>";
            window.print();
            document.body.innerHTML = originalContents;
        }
    </script>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <div class="sidebar">
    <h2 style="text-align:center;">Admin Panel</h2>
    <a href="dashboard.aspx">Dashboard</a>
    <a href="ManageGallery.aspx">Manage Gallery</a>
    <a href="upload_reviews.aspx">Manage Reviews</a>
    <a href="Notice.aspx">Manage Notice</a>
                <a href="uploadteammember.aspx">Manage Team Members</a>
    <a href="logout.aspx">Logout</a>
</div>
<div class="main-content" id="contents">
    <center><h2>Batch Registration</h2>

            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Id" DataSourceID="SqlDataSource1" BackColor="White" BorderColor="#336666" BorderStyle="Double" BorderWidth="3px" CellPadding="4" GridLines="Horizontal">
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                    <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                    <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                    <asp:BoundField DataField="Contact" HeaderText="Contact" SortExpression="Contact" />
                
                    <asp:BoundField DataField="BatchTiming" HeaderText="BatchTiming" SortExpression="BatchTiming" />
                    <asp:BoundField DataField="FromDate" HeaderText="FromDate" SortExpression="FromDate" />
                </Columns>
                <FooterStyle BackColor="White" ForeColor="#333333" />
                <HeaderStyle BackColor="#336666" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#336666" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="White" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#339966" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F7F7F7" />
                <SortedAscendingHeaderStyle BackColor="#487575" />
                <SortedDescendingCellStyle BackColor="#E5E5E5" />
                <SortedDescendingHeaderStyle BackColor="#275353" />
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:MyConnectionString %>" SelectCommand="SELECT Id,Name,Email,Contact,BatchTiming,FromDate FROM BatchReg" DeleteCommand="DELETE FROM BatchReg WHERE (Id=@id)" UpdateCommand="UPDATE BatchReg SET Name=@Name,Email=@Email,Contact=@Contact,BatchTiming=@BatchTiming,FromDate=@FromDate WHERE (Id=@Id)">
                <DeleteParameters>
                    <asp:Parameter Name="Id" Type="Int32" />
                </DeleteParameters>
                <UpdateParameters>
                    <asp:Parameter Name="Name" Type="String" />
                    <asp:Parameter Name="Email" Type="String" />
                    <asp:Parameter Name="Contact" Type="String" />
                  
                    <asp:Parameter Name="BatchTiming" Type="String" />
                    <asp:Parameter Name="FromDate" Type="String" />
                </UpdateParameters>
            </asp:SqlDataSource>
        <asp:Button ID="btn_pdf" Text="Download" runat="server" OnClientClick="PrintDiv();return false;" />

        </center>
        </div>
    </form>
</body>
</html>
